version: "3.8"

services:
  app:
    container_name: pbkk-app-web
    image: dptsi/laravel-web-dev
    volumes: 
      - ./src/:/var/www/html
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - DEFAULT_HOST=${VIRTUAL_PORT}
      - SELF_SIGNED_HOST=${SELF_SIGNED_HOST}
    dns:
      - 1.1.1.1
      - 1.0.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nginx-proxy-network

  mysql:
    image: mysql:8.0
    container_name: pbkk-mysql
    ports:
      - "3006:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_myitsbooking
      - MYSQL_USER=myitsbooking
      - MYSQL_PASSWORD=myitsbooking
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
